apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "40"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"generation":1,"labels":{"app":"go"},"name":"go-demo","namespace":"default"},"spec":{"progressDeadlineSeconds":600,"replicas":3,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"go"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"go"}},"spec":{"automountServiceAccountToken":true,"containers":[{"image":"europe-central2-docker.pkg.dev/ethereal-runner-417315/dc-docker-repo/demo_app:production","imagePullPolicy":"Always","name":"dchernenko-demo-app","ports":[{"containerPort":8088,"protocol":"TCP"}],"resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"dnsPolicy":"ClusterFirst","enableServiceLinks":true,"restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"shareProcessNamespace":false,"terminationGracePeriodSeconds":30}}},"status":{"availableReplicas":3,"observedGeneration":1,"readyReplicas":3,"replicas":3,"updatedReplicas":3}}
  creationTimestamp: "2024-03-16T20:43:25Z"
  generation: 50
  labels:
    app: go
  name: go-demo
  namespace: default
  resourceVersion: "20385014"
  uid: 4d6555be-2795-40ca-86ad-b56efc7603c4
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: go
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2024-04-14T20:35:22Z"
      creationTimestamp: null
      labels:
        app: go
    spec:
      automountServiceAccountToken: true
      containers:
      - image: europe-central2-docker.pkg.dev/ethereal-runner-417315/dc-docker-repo/demo_app:production
        imagePullPolicy: Always
        name: dchernenko-demo-app
        ports:
        - containerPort: 8088
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      shareProcessNamespace: false
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 3
  conditions:
  - lastTransitionTime: "2024-04-14T16:32:17Z"
    lastUpdateTime: "2024-04-14T16:32:17Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2024-03-19T12:09:35Z"
    lastUpdateTime: "2024-04-14T20:35:33Z"
    message: ReplicaSet "go-demo-cd6495b86" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 50
  readyReplicas: 3
  replicas: 3
  updatedReplicas: 3
