apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dok-tele-status-demo.fullname" . }}-tele-token
  labels:
    {{- include "dok-tele-status-demo.labels" . | nindent 4 }}
type: Opaque
data:
  teleToken: {{ .Values.dokTeleStatusDemo.dokTeleStatus.env.teleToken | b64enc }}
