apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: coffee-monitor
spec:
  schedule: "*/15 * * * *" # Runs every 15 minutes
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: coffee-monitor
              image: coffee-monitor:latest
              env:
                - name: COFFEE_PRICE_URL
                  value: "https://api.coffeeprice.com/latest"
              command: ["/bin/sh", "-c", "if [ $(curl -s $COFFEE_PRICE_URL | jq '.price') -gt 5 ]; then kubectl scale deployment go-demo --replicas=1; fi"] # Scale down deployment if coffee price is above 5
          restartPolicy: OnFailure
