apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "31"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"generation":1,"labels":{"app":"go"},"name":"go-demo","namespace":"default"},"spec":{"progressDeadlineSeconds":600,"replicas":5,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"go"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"go"}},"spec":{"automountServiceAccountToken":true,"containers":[{"image":"europe-central2-docker.pkg.dev/ethereal-runner-417315/dc-docker-repo/demo_app:production","imagePullPolicy":"Always","name":"dchernenko-demo-app","ports":[{"containerPort":8088,"protocol":"TCP"}],"resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"dnsPolicy":"ClusterFirst","enableServiceLinks":true,"restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"shareProcessNamespace":false,"terminationGracePeriodSeconds":30}}},"status":{"availableReplicas":5}}
  creationTimestamp: "2024-03-16T20:43:25Z"
  generation: 37
  labels:
    app: go
  name: go-demo
  namespace: default
  resourceVersion: "17245106"
  uid: 4d6555be-2795-40ca-86ad-b56efc7603c4
spec:
  replicas: 5
  selector:
    matchLabels:
      app: go
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go
    spec:
      automountServiceAccountToken: true
      containers:
      - image: europe-central2-docker.pkg.dev/ethereal-runner-417315/dc-docker-repo/demo_app:production
        imagePullPolicy: Always
        name: dchernenko-demo-app
        ports:
        - containerPort: 8088
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      shareProcessNamespace: false
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 5
